### ISSUE TITLE
[FEAT] Get duration from read(bytes)

### ISSUE THREAD

**Issue by PcolBP** [liamappelbe/wav#4]
Is it possible to get duration of wav file?

**Comment by gnudles** [comment]
Divide the total number of samples, by the sample-rate,  and you will get the number of seconds. I also wrote such wav library for dart, it is called wav_io, but unfortunately it did not got popular.

**Comment by liamappelbe** [comment]
Yeah, you can just divide the number of samples by the samples per second, but I should really add a helper method for this.

**Comment by liamappelbe** [comment]
Done. Update to 1.2.0 and you'll see the duration method
